version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: larse514/circle-ci-node-docker:latest
    # environment:
    #   - BUCKET_NAME: "moodle.sites.lambda.deployment"
    environment:
      - AMAZONIAN_DIST: "https://s3.amazonaws.com/amazonian.package.release/latest/amazonian"
      - HOSTED_ZONE: "vssdevelopment.com"
      - IMAGE: "projectfeedme/feed-me-ui:dev"
      - PortMapping: 4200

    steps:
    - checkout
    - setup_remote_docker:   # (2)
        docker_layer_caching: true # (3)
    # use a primary image that already has Docker (recommended)
    # or install it during a build like we do here
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    # - run:
    #     name: install-npm-wee
    #     command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    # - run:
    #   name: lint roll
    #   command: 'npm run lint'
    # - run:
    #     name: run unit tests
    #     command: 'npm test'
    - run:
        name: build docker image
        command: 'npm run docker-build'
    - run: 
        name: install amazonian
        command: |
            wget ${AMAZONIAN_DIST}
            chmod +x amazonian
    - run: 
        name: Configure AWS environment
        command: |
            aws configure set default.region us-east-1
            aws configure set default.output json
    - run:
        name: Docker login
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Docker Push
        command: npm run docker-push
    - run: 
        name: deploy dev
        command: ./amazonian --HostedZoneName=${HOSTED_ZONE} --Image=${IMAGE} --PortMapping=${PortMapping} --VPCName=feedme-dev ClusterName=feedmecluser-dev
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: test-results.xml