version: 2
jobs:
  #####################################################
  ## Build Definition (MASTER and FEATURE branches only)
  #####################################################
  build:
    branches:
      only:
        - master
        - feature*
    docker:
      - image: larse514/circle-ci-node-docker:latest
    environment:

    steps:
    - checkout
    - setup_remote_docker:   # (2)
        docker_layer_caching: true # (3)
    # use a primary image that already has Docker (recommended)
    # or install it during a build like we do here
    # - run:
    #     name: update-npm
    #     command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    # - run:
    #     name: install-npm-wee
    #     command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: build docker image
        command: 'npm run docker-build'
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: test-results.xml

  deploy:
    branches:
      only:
        - master
    docker:
      - image: larse514/circle-ci-node-docker:latest
    environment:
      - AMAZONIAN_DIST: "https://s3.amazonaws.com/amazonian.package.release/latest/amazonian"
      - HOSTED_ZONE: "vssdevelopment.com"
      - IMAGE: "projectfeedme/feed-me-ui:dev"
      - PORT_MAPPING: 4200
    steps:
    - setup_remote_docker:   # (2)
        docker_layer_caching: true # (3)
    - run: 
        name: install amazonian
        command: |
            wget ${AMAZONIAN_DIST}
            chmod +x amazonian
    - run: 
        name: Configure AWS environment
        command: |
            aws configure set default.region us-east-1
            aws configure set default.output json
    - run:
        name: Docker login
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Docker Push
        command: npm run docker-push
    - run: 
        name: deploy dev
        command: |
            chmod +x deploy.sh
            ./deploy.sh ${HOSTED_ZONE} ${IMAGE} ${PORT_MAPPING} feedme-dev feedmecluser-dev simpleyfed
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build